version: '3.8'
services:
    redis:
        container_name: redis-server
        image: redis:alpine
        restart: always
        command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
        env_file:
          - redis.env
